### ISSUE TITLE
27.4.2 Patch Notes - DeckDiff Not valid deckcode

### ISSUE THREAD

**Issue by Shouclack** [HearthSim/npm-deckstrings#12]
Since the last patch DeckDiff which depends on hearthstone-deckstrings stopped working giving error "This is not a valid deckcode"

**Comment by beheh** [comment]
@Shouclack Do you have a working example of such a deck code and the input you used to generate it?

**Comment by Shouclack** [comment]
### Custom Rogue
# Class: Rogue
# Format: Standard
# Year of the Wolf
#
# 2x (0) Preparation
# 1x (0) Shadow of Demise
# 2x (0) Shadowstep
# 2x (1) Air Guitarist
# 2x (1) Deadly Poison
# 2x (1) Gear Shift
# 2x (1) Ghostly Strike
# 2x (1) Gone Fishin'
# 2x (2) Eviscerate
# 2x (2) Harmonic Hip Hop
# 2x (2) Potion Belt
# 2x (2) Serrated Bone Spike
# 2x (2) Tentacle Grip
# 2x (3) Mic Drop
# 2x (4) Prison Breaker
# 1x (15) Yogg-Saron, Unleashed
# 
AAECAZurBALMoAWplQYOkp8E9p8E958Et7ME9d0E36AFwaEF07IF2sMF0s4Fv/cFtZkGwpoGvZ4GAAA=
# 
# To use this deck, copy it to your clipboard and create a new deck in Hearthstone

**Comment by beheh** [comment]
Sorry, I will need more context. It's possible this is simply due to an issue with DeckDiff (I'm not familiar with it) or they're using a too old tool. To proceed I will need the specific calls to this library and the deckstring that doesn't work as expected.
