### ISSUE TITLE
Hearthstone cannot automatically recognize  code 

### ISSUE THREAD

**Issue by imyanglu** [HearthSim/npm-deckstrings#13]
The Hearthstone game cannot automatically recognize the generated code, but the official website can parse it correctly. Can you tell me why? I just started using this library。I think there should be something wrong with the way I'm using it, but the documentation is simple so I don't know where I'm going wrong。thank U :)
code:AAECAbyKBAAPn58EtJ8EhqAEiaAE8M0F6tAF5OQFtfgFl/sFy/sFkJcGnJ4G6Z4G4+YG5OYGAAA=
i copy the code,but hearthstone game cannot automatically recognize the generated code.

**Comment by beheh** [comment]
Hi there! What are the inputs you used to generate this deck code?

**Comment by imyanglu** [comment]
> Hi there! What are the inputs you used to generate this deck code?

this is code AAECAQUGwcQFjf4Fx6QG06kGus4G5uYGDMmgBKLUBJT1BZX1BYWOBpmOBryPBvWVBs6cBtSeBpKgBt66BgABA/OzBsekBvazBsekBujeBsekBgAA this is params {"cards":[[100101,2],[105822,2],[103635,1],[101966,2],[69705,2],[98061,1],[96916,2],[102418,2],[101109,2],[76322,2],[90689,1],[102983,1],[102228,2],[96917,2],[100121,2],[111462,1],[100284,2],[108346,1]],"sideboardCards":[[110440,1,102983],[104947,1,102983],[104950,1,102983]],"heroes":[5],"format":2}

**Comment by imyanglu** [comment]
> Hi there! What are the inputs you used to generate this deck code?

thankq this my false
