### ISSUE TITLE
Unable to parse latest deckstrings

### ISSUE THREAD

**Issue by stevenjoezhang** [HearthSim/npm-deckstrings#5]
Hi there, I am a Hearthstone gamer and have tried to use this library to parse the deckstrings. After installing it using `npm i deckstrings`, I ran the following code
```js
const { decode } = require("deckstrings");
var deckstring = "AAECAaIHHrQBsgLtAs0DrwSIB8f4AqCAA7SGA7SRA4+XA5CXA5KXA/uaA/6aA/yjA4SnA/WnA7euA7muA8GuA/6uA6qvA86vA/2wA4KxA5GxA+O0A5+3A8vAAwAA";
var deck = decode(deckstring);
```
However it throws an exception:

```
RangeError: Could not decode varint
    at Object.read [as decode] (/root/hearthstone-deck/node_modules/deckstrings/dist/index.js:50:13)
    at BufferReader.nextVarint (/root/hearthstone-deck/node_modules/deckstrings/dist/index.js:162:28)
    at decode$2 (/root/hearthstone-deck/node_modules/deckstrings/dist/index.js:276:24)
    at module.exports (/root/hearthstone-deck/core.js:102:14)
    at /root/hearthstone-deck/server.js:40:12
    at Layer.handle [as handle_request] (/root/hearthstone-deck/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/hearthstone-deck/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/hearthstone-deck/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/hearthstone-deck/node_modules/express/lib/router/layer.js:95:5)
    at /root/hearthstone-deck/node_modules/express/lib/router/index.js:281:22
```

Then I found the Hearthstone deckstring at different times on a game forum for analysis, and the results seem to prove that the deckstring after `Saviors of Uldum` was released, could not be parsed.

| Date | Deckstring / event | Result |
| - | - | - |
| July 20 | `AAECAf0ECqQDkAe4CLwI7vYCw/gCxvgCoIADlpoDn7cDCqsE5gThB40IyIcD0okDg5YDn5sD4psD/50DAA==` | Success |
| August 01 | `AAECAf0EAu72Ar6kAw5xwwG7AqsE5gSWBewFvAjIhwOfmwPimwO/pAPdqQP0qwMA` | Success |
| August 06 | **`Saviors of Uldum` Released** | N/A |
| August 17 | `AAECAR8engGoArUDxwOHBMkErgaKB+UHlwjFCNsJ/gyY8AKA8wKggAOnggObhQOghQP1iQPmlgP5lgO+mAO2nAP8owOfpQOipQOmpQOEpwOftwMAAA==` | Failure |
| December 01 | `AAECAZICDLQDrtICv/IC5PsC9fwC2p0D+KEDyKID3KID9KID/bYD1dIDCUBWX/4B0wPEBqmiA++iA9mpAwA=` | Failure |
| December 30 | `AAECAaIHHrQBsgLtAs0DrwSIB8f4AqCAA7SGA7SRA4+XA5CXA5KXA/uaA/6aA/yjA4SnA/WnA7euA7muA8GuA/6uA6qvA86vA/2wA4KxA5GxA+O0A5+3A8vAAwAA` | Failure |

 I'm not sure if this is because Blizzard modified the algorithm. Could anyone help me?

**Comment by beheh** [comment]
Are you sure you're on the latest version of `deckstrings` and the line you shared is the one throwing the exception? Your string decodes for me:
![image](https://user-images.githubusercontent.com/929769/73474851-70cba500-438f-11ea-9855-52dc4f2b882e.png)

**Comment by stevenjoezhang** [comment]
Ah, I found that I made a mistake. There was a bug in other code I wrote, which caused the plus sign `+` to be escaped, so base64 parsed the wrong result. This module works like a charm now. Thank you for your help!
